# fly.toml file generated for safetyjim on 2022-07-07T15:29:11+03:00

app = "safetyjim"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  strategy = "rolling"
  restart_policy = "on_failure"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 99999
    soft_limit = 99999
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    grace_period = "1m"
    interval = "1m"
    method = "GET"
    timeout = "5s"
    path = "/health_check"
