create table if not exists settings
(
    guild_id                                 bigint  not null primary key,
    mod_log                                  boolean not null,
    mod_log_channel_id                       bigint  not null,
    report_channel_id                        bigint  not null,
    holding_room                             boolean not null,
    holding_room_role_id                     bigint,
    holding_room_minutes                     integer not null,
    invite_link_remover                      boolean not null,
    welcome_message                          boolean not null,
    message                                  text    not null,
    welcome_message_channel_id               bigint  not null,
    join_captcha                             boolean not null,
    word_filter                              boolean not null,
    word_filter_blocklist                    text,
    word_filter_level                        integer not null,
    word_filter_action                       integer not null,
    word_filter_action_duration              integer not null,
    word_filter_action_duration_type         integer not null,
    invite_link_remover_action               integer not null,
    invite_link_remover_action_duration      integer not null,
    invite_link_remover_action_duration_type integer not null,
    privacy_settings                         integer not null,
    privacy_mod_log                          integer not null,
    softban_threshold                        integer not null,
    softban_action                           integer not null,
    softban_action_duration                  integer not null,
    softban_action_duration_type             integer not null,
    kick_threshold                           integer not null,
    kick_action                              integer not null,
    kick_action_duration                     integer not null,
    kick_action_duration_type                integer not null,
    mute_threshold                           integer not null,
    mute_action                              integer not null,
    mute_action_duration                     integer not null,
    mute_action_duration_type                integer not null,
    warn_threshold                           integer not null,
    warn_action                              integer not null,
    warn_action_duration                     integer not null,
    warn_action_duration_type                integer not null,
    mods_can_edit_tags                       boolean not null,
    spam_filter                              boolean not null
);